# Generated by Django 4.0.4 on 2022-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'male'), ('Female', 'female')], max_length=25)),
                ('address', models.CharField(max_length=500)),
                ('aadhaar', models.FileField(upload_to='')),
                ('img', models.ImageField(default=None, null=True, upload_to='')),
                ('medHistory', models.CharField(max_length=500)),
                ('transectionDone', models.FloatField(default=0)),
                ('transectionDue', models.FloatField(default=0)),
                ('billCopy', models.FileField(upload_to='')),
                ('labReport', models.FileField(upload_to='')),
                ('symptoms', models.CharField(max_length=500)),
            ],
        ),
    ]
