# Generated by Django 4.0.4 on 2022-05-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='userRestDetailsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('Female', 'female')], max_length=25)),
                ('mobile', models.IntegerField()),
                ('account', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
